<?php

namespace App\Reports;

use App\Models\Booking;
use App\Models\Court;
use App\Models\Payment;
use Barryvdh\DomPDF\Facade\Pdf;
use Barryvdh\DomPDF\PDF as DomPdfInstance;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB;

/**
 * Class BookingReportPdf
 *
 * Reusable PDF report generator for Court Owners & Venue Managers.
 *
 * ARCHITECTURAL TRADE-OFF NOTE (Requirement 5):
 * -------------------------------------------------------------
 * PDF generation via DOMPDF requires rendering HTML/CSS into vector pages.
 * For executive summaries (covering 1 week to 1 month of operations),
 * synchronous rendering is fast (< 1s) and straightforward.
 *
 * For extremely large transaction tables (thousands of pages), direct
 * synchronous PDF generation can risk PHP memory limits. In such enterprise
 * scenarios, the recommended pattern is dispatching a queue job (e.g. `GeneratePdfReportJob`),
 * splitting tables across paginated chunks or storing the compiled PDF in S3 storage,
 * then notifying the user with a download link.
 */
class BookingReportPdf
{
    protected const DAILY_HOURS_PER_COURT = 16;

    public function __construct(
        protected Carbon $startDate,
        protected Carbon $endDate
    ) {}

    /**
     * Gather and aggregate all metrics needed for the PDF report.
     */
    public function getData(): array
    {
        $startStr = $this->startDate->format('Y-m-d');
        $endStr = $this->endDate->format('Y-m-d');

        // Total Days in period
        $daysCount = max(1, $this->startDate->diffInDays($this->endDate) + 1);

        // 1. Total revenue from payments marked paid
        $totalRevenue = (float) Payment::where('status', 'paid')
            ->whereBetween('paid_at', [
                $this->startDate->copy()->startOfDay(),
                $this->endDate->copy()->endOfDay(),
            ])
            ->sum('amount');

        // 2. Booking status counts
        $bookingsQuery = Booking::whereBetween('booking_date', [$startStr, $endStr]);
        $totalBookings = (clone $bookingsQuery)->count();
        $confirmedBookings = (clone $bookingsQuery)->whereIn('status', ['confirmed', 'completed'])->count();
        $pendingBookings = (clone $bookingsQuery)->where('status', 'pending')->count();
        $cancelledBookings = (clone $bookingsQuery)->where('status', 'cancelled')->count();

        // 3. Court-by-court breakdown (Occupancy, Bookings, Hours, Revenue)
        $courts = Court::where('is_active', true)->orderBy('name')->get();
        $courtStats = [];

        foreach ($courts as $court) {
            $courtCapacity = $daysCount * self::DAILY_HOURS_PER_COURT;

            // Total hours booked (non-cancelled)
            $hoursBooked = (float) Booking::where('court_id', $court->id)
                ->where('status', '!=', 'cancelled')
                ->whereBetween('booking_date', [$startStr, $endStr])
                ->selectRaw('COALESCE(SUM(TIME_TO_SEC(TIMEDIFF(end_time, start_time)) / 3600), 0) as total_hours')
                ->value('total_hours');

            $bookingsCount = Booking::where('court_id', $court->id)
                ->where('status', '!=', 'cancelled')
                ->whereBetween('booking_date', [$startStr, $endStr])
                ->count();

            // Revenue generated by this court (paid payments)
            $courtRevenue = (float) Payment::where('status', 'paid')
                ->whereHas('booking', function ($q) use ($court, $startStr, $endStr) {
                    $q->where('court_id', $court->id)
                      ->whereBetween('booking_date', [$startStr, $endStr]);
                })
                ->sum('amount');

            $occupancyRate = $courtCapacity > 0 ? round(($hoursBooked / $courtCapacity) * 100, 1) : 0;

            $courtStats[] = [
                'name' => $court->name,
                'price_per_hour' => (float) $court->price_per_hour,
                'bookings_count' => $bookingsCount,
                'hours_booked' => $hoursBooked,
                'capacity_hours' => $courtCapacity,
                'occupancy_rate' => $occupancyRate,
                'revenue' => $courtRevenue,
            ];
        }

        // Overall occupancy rate across all active courts
        $totalActiveCourts = count($courts);
        $totalArenaCapacity = $totalActiveCourts * $daysCount * self::DAILY_HOURS_PER_COURT;
        $totalArenaHoursBooked = array_sum(array_column($courtStats, 'hours_booked'));
        $overallOccupancyRate = $totalArenaCapacity > 0 ? round(($totalArenaHoursBooked / $totalArenaCapacity) * 100, 1) : 0;

        // 4. Sample / Full list of transactions for this period
        $bookingsList = Booking::with(['user', 'court', 'payment'])
            ->whereBetween('booking_date', [$startStr, $endStr])
            ->orderBy('booking_date', 'desc')
            ->orderBy('start_time', 'desc')
            ->get();

        return [
            'periodLabel' => $this->startDate->translatedFormat('d M Y') . ' — ' . $this->endDate->translatedFormat('d M Y'),
            'startDate' => $this->startDate->translatedFormat('d F Y'),
            'endDate' => $this->endDate->translatedFormat('d F Y'),
            'daysCount' => $daysCount,
            'generatedAt' => now()->translatedFormat('d F Y, H:i') . ' WIB',
            'totalRevenue' => $totalRevenue,
            'totalBookings' => $totalBookings,
            'confirmedBookings' => $confirmedBookings,
            'pendingBookings' => $pendingBookings,
            'cancelledBookings' => $cancelledBookings,
            'courtStats' => $courtStats,
            'totalArenaHoursBooked' => $totalArenaHoursBooked,
            'totalArenaCapacity' => $totalArenaCapacity,
            'overallOccupancyRate' => $overallOccupancyRate,
            'bookingsList' => $bookingsList,
        ];
    }

    /**
     * Generate the DomPDF instance.
     */
    public function generate(): DomPdfInstance
    {
        $data = $this->getData();

        return Pdf::loadView('reports.booking-summary-pdf', $data)
            ->setPaper('a4', 'portrait')
            ->setOptions([
                'isHtml5ParserEnabled' => true,
                'isRemoteEnabled' => true,
                'defaultFont' => 'sans-serif',
            ]);
    }

    /**
     * Download the PDF report as a streamable file.
     */
    public function download(?string $filename = null)
    {
        $filename ??= 'Laporan-SmashArena-' . $this->startDate->format('Ymd') . '-' . $this->endDate->format('Ymd') . '.pdf';

        return $this->generate()->download($filename);
    }

    /**
     * Stream the PDF report in browser.
     */
    public function stream(?string $filename = null)
    {
        $filename ??= 'Laporan-SmashArena-' . $this->startDate->format('Ymd') . '-' . $this->endDate->format('Ymd') . '.pdf';

        return $this->generate()->stream($filename);
    }
}

